name: manual_redeploy


on:
  
  workflow_dispatch:
    inputs:
      version:
        description: Número de release o pre-release a redesplegar.
        required: true
        type: string
      ambiente:
        description: Ambiente al cual se va a redesplegar.
        required: true
        type: choice
        options:
          - develop
          - preprod
          - production
      dynamodb:
        description: 'Activa la insercion de datos de la carpeta tablas DynamoDB ⚠️ CUIDADO: Validar que la inserción en tablas no afecta a otros procesos.'
        required: false
        default: false
        type: boolean
  
jobs:

  RedeployDev:
    concurrency: develop
    if: ${{github.event.inputs.ambiente == 'develop'}}
    uses: principalmexico-emu/SAUTO_CICD/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      ref: ${{github.event.inputs.version}}
      region: us-east-1
      region_dr: us-west-2
      dynamodb: ${{github.event.inputs.dynamodb}}
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.SIA_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.SIA_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.SIA_DEV_AWS_ACCOUNT_ID}}

  RedeployPre:
    concurrency: preprod
    if: ${{github.event.inputs.ambiente == 'preprod'}}
    uses: principalmexico-emu/SAUTO_CICD/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "preprod"
      ref: ${{github.event.inputs.version}}
      region: us-east-1
      region_dr: us-west-2
      dynamodb: ${{github.event.inputs.dynamodb}}
    secrets:
      PRE_AWS_KEY_ID: ${{ secrets.SIA_PRE_AWS_KEY_ID}}
      PRE_AWS_KEY_SECRET: ${{ secrets.SIA_PRE_AWS_KEY_SECRET}}
      PRE_AWS_ACCOUNT_ID: ${{ secrets.SIA_PRE_AWS_ACCOUNT_ID}}

  RedeployProd:
    concurrency: production
    if: ${{github.event.inputs.ambiente == 'production'}}
    uses: principalmexico-emu/SAUTO_CICD/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "production"
      ref: ${{github.event.inputs.version}}
      region: us-east-1
      region_dr: us-west-2
      dynamodb: ${{github.event.inputs.dynamodb}}
    secrets:
      PROD_AWS_KEY_ID: ${{ secrets.AWS_KEY}}
      PROD_AWS_KEY_SECRET: ${{ secrets.AWS_SECRET}}
      PROD_AWS_ACCOUNT_ID: ${{ secrets.AWS_ID}}
